
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "voltaserve-idp.fullname" . }}
data:
  {{- if .Values.idp.envs }}
    {{- range $k,$v := .Values.idp.envs }}
      {{$k }}: {{ default "" $v | quote }}
    {{- end }}
  {{- end }}
  SMTP_HOST: {{ .Values.general.smtp.SMTP_HOST | quote}}
  SMTP_PORT: {{ .Values.general.smtp.SMTP_PORT | quote}}
  SMTP_SENDER_ADDRESS: {{ .Values.general.smtp.SMTP_SENDER_ADDRESS | quote}}
  SMTP_SENDER_NAME: {{ .Values.general.smtp.SMTP_SENDER_NAME | quote}}
  SMTP_SECURE: {{ .Values.general.smtp.SMTP_SECURE | quote }}
  {{- if .Values.meilisearch.enabled }}
  SEARCH_URL: http://{{ include "voltaserve.fullname" . }}-meilisearch.{{.Release.Namespace}}.svc.{{ .Values.clusterDomain | default cluster.local }}:{{ default .Values.meilisearch.service.port 7700 }}
  {{- else }}
  SEARCH_URL: {{ .Values.general.envs.SEARCH_URL }}
  {{- end  }}
  {{- if .Values.cockroachdb.enabled }}
  POSTGRES_URL: postgresql://voltaserve@{{ include "voltaserve.fullname" . }}-cockroachdb:26257/voltaserve # to be updated by user for dynamic parsing
  {{- else }}
  POSTGRES_URL: {{ .Values.general.envs.POSTGRES_URL }}
  {{- end  }}
  {{- if .Values.ui.ingress.enabled }}
  PUBLIC_UI_URL: https://{{ .Values.ui.ingress.host }}
  TOKEN_ISSUER: https://{{ .Values.ui.ingress.host }}
  SECURITY_CORS_ORIGINS: https://{{ .Values.ui.ingress.host }}
  {{- else }}
  PUBLIC_UI_URL: {{ .Values.general.envs.PUBLIC_UI_URL }}
  SECURITY_CORS_ORIGINS: {{ .Values.general.envs.PUBLIC_UI_URL }}
  TOKEN_ISSUER: {{ .Values.general.envs.PUBLIC_UI_URL }}
  {{- end  }}