apiVersion: v1
kind: Secret
metadata:
  name: {{ include "voltaserve-idp.fullname" . }}
type: Opaque
data:
  {{- if .Values.general.secrets.sharedSecrets }}
    {{- range $k,$v := .Values.general.sharedEnvs }}
      {{$k }}: {{ default "" $v | b64enc | quote }}
    {{- end }}
  {{- end }}
  SMTP_USERNAME: {{ .Values.general.secrets.smtp.SMTP_USERNAME | b64enc | quote }}
  SMTP_PASSWORD: {{ .Values.general.secrets.smtp.SMTP_PASSWORD | b64enc | quote }}