apiVersion: v1
kind: Service
metadata:
  name: {{ include "voltaserve-idp.fullname" . }}
  labels:
    {{- include "voltaserve-idp.labels" . | nindent 4 }}
  {{- with .Values.idp.service.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  ipFamilyPolicy: SingleStack
  type: {{ .Values.idp.service.type }}
  clusterIP: "None"
  ports:
    - port: {{ .Values.idp.service.port }}
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    {{- include "voltaserve-idp.selectorLabels" . | nindent 6 }}