apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "voltaserve-webdav.fullname" . }}
data:
  {{- if .Values.webdav.envs }}
    {{- range $k,$v := .Values.webdav.envs }}
      {{$k }}: {{ default "" $v | quote }}
    {{- end }}
  {{- end }}
  IDP_URL: http://{{ include "voltaserve-idp.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.idp.service.port }}
  API_URL: http://{{ include "voltaserve-api.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.api.service.port }}

