apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "voltaserve.fullname" . }}-webdav
data:
  {{- if .Values.webdav.envs }}
    {{- range $k,$v := .Values.webdav.envs }}
      {{$k }}: {{ default "" $v | quote }}
    {{- end }}
  {{- end }}
  PORT: {{ .Values.webdav.service.targetPort | quote }}
  IDP_URL: http://{{ include "voltaserve.fullname" . }}-idp.{{ .Release.Namespace }}.svc.cluster.local:8081
  API_URL: http://{{ include "voltaserve.fullname" . }}-api.{{ .Release.Namespace }}.svc.cluster.local:8080

