apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "voltaserve.fullname" . }}-webdav
data:
  {{- if .Values.webdav.envs }}
    {{- range $k,$v := .Values.webdav.envs }}
      {{$k }}: {{ default "" $v | quote }}
    {{- end }}
  {{- end }}
  IDP_URL: http://{{ include "voltaserve.fullname" . }}-idp.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.idp.service.port }}
  API_URL: http://{{ include "voltaserve.fullname" . }}-api.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.api.service.port }}

