apiVersion: v1
kind: Secret
metadata:
  name: {{ include "voltaserve-webdav.fullname" . }}
type: Opaque
data:
  {{- if .Values.general.secrets.sharedSecrets }}
    {{- range $k,$v := .Values.general.sharedEnvs }}
      {{$k }}: {{ default "" $v | b64enc | quote }}
    {{- end }}
  {{- end }}
  S3_ACCESS_KEY: {{ .Values.general.secrets.s3.S3_ACCESS_KEY | default "voltaserve" | b64enc | quote }}
  S3_SECRET_KEY: {{ .Values.general.secrets.s3.S3_SECRET_KEY | default "voltaserve" | b64enc | quote }}
