apiVersion: v1
kind: Service
metadata:
  name: {{ include "voltaserve-webdav.fullname" . }}
  labels:
    {{- include "voltaserve-webdav.labels" . | nindent 4 }}
spec:
  ipFamilyPolicy: SingleStack
  type: {{ .Values.webdav.service.type }}
  clusterIP: "None"
  ports:
    - port: {{ .Values.webdav.service.port }}
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    {{- include "voltaserve-webdav.selectorLabels" . | nindent 6 }}