apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "voltaserve.fullname" . }}-conversion
data:
  {{- if .Values.conversion.envs }}
    {{- range $k,$v := .Values.conversion.envs }}
      {{$k }}: {{ default "" $v | quote }}
    {{- end }}
  {{- end }}
  API_URL: http://{{ include "voltaserve.fullname" . }}-api.{{.Release.Namespace}}.svc.cluster.local:{{ .Values.api.service.port }}
  LANGUAGE_URL: http://{{ include "voltaserve.fullname" . }}-language.{{.Release.Namespace}}.svc.cluster.local:{{ .Values.language.service.port }}
  MOSAIC_URL: http://{{ include "voltaserve.fullname" . }}-mosaic.{{.Release.Namespace}}.svc.cluster.local:{{ .Values.mosaic.service.port }}
  {{- if .Values.minio.enabled }}
  S3_URL: {{ include "voltaserve.fullname" . }}-minio.{{ .Release.Namespace }}.svc.cluster.local:9000
  {{- else }}
  S3_URL: {{ .Values.general.envs.S3_URL }}
  {{- end  }}
  S3_SECURE: {{ .Values.general.envs.S3_SECURE | quote }}