apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voltaserve-conversion.fullname" . }}
  labels:
    {{- include "voltaserve-conversion.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.conversion.deployment.replicaCount | default 1}}
  selector:
    matchLabels:
      {{- include "voltaserve-conversion.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/conversion/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/conversion/secret.yaml") . | sha256sum }}
        checksum/secret-api: {{ include (print $.Template.BasePath "/sharedSecrets/secret.yaml") . | sha256sum }}
          {{- with .Values.conversion.deployment.podAnnotations }}
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with (.Values.globals).podAnnotations }}
            {{- toYaml . | nindent 8 }}
          {{- end }}
      labels:
        {{- include "voltaserve-conversion.labels" . | nindent 8 }}
        {{- with .Values.conversion.deployment.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.imagePullSecrets }}
        {{- with .Values.imagePullSecrets }}
        imagePullSecrets:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if .Values.conversion.deployment.security }}
      {{- if .Values.conversion.deployment.security.securityContext }}
      securityContext:
        {{- toYaml .Values.conversion.deployment.security.securityContext | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
        - name: main
          {{- if .Values.conversion.deployment.security }}
          {{- if .Values.conversion.deployment.security.podSecurityContext }} 
          securityContext:
            {{- toYaml .Values.conversion.deployment.security.podSecurityContext | nindent 12 }}
          {{- end }}
          {{- end }}
          image: {{ .Values.conversion.image.repository | default "voltaserve/conversion" }}:{{ .Values.conversion.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.conversion.deployment.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: 8083
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.conversion.deployment.livenessProbePath | default "/v2/health" }}
              port: 8083
            initialDelaySeconds: 300
          readinessProbe:
            httpGet:
              path: {{ .Values.conversion.deployment.readinessProbePath | default "/v2/health" }}
              port: 8083
            initialDelaySeconds: 15
          {{- if .Values.conversion.deployment.resources }}
          resources:
            {{- toYaml .Values.conversion.deployment.resources | nindent 12 }}
          {{- end }}
          {{- with .Values.conversion.deployment.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
          - configMapRef:
              name: {{ include "voltaserve-conversion.fullname" . }}
          - secretRef:
              name: {{ include "voltaserve-conversion.fullname" . }}
          - secretRef:
              name: {{ include "voltaserve.fullname" . }}-security-apikey
          {{- if .Values.conversion.existingSecret }}
          - secretRef:
              name: {{ .Values.conversion.existingSecret }}
          {{- end }}
      {{- with .Values.conversion.deployment.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.conversion.deployment.nodeSelector (.Values.globals).nodeSelectors }}
      nodeSelector:
      {{- with .Values.conversion.deployment.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (.Values.globals).nodeSelectors }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.conversion.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.conversion.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}