{{- if .Values.cockroachdb.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "voltaserve.fullname" . }}-cockroachdb-initjob
  labels:
    {{- include "voltaserve.commonLabels" . | nindent 4 }}
  annotations:
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        {{- include "voltaserve.commonLabels" . | nindent 8 }}
        {{- with .Values.cockroachdb.initJob.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: {{ include "voltaserve.fullname" . }}-cockroachdb-initjob
        image: postgres:13-alpine
        command:
          - sh
          - -c
          - >
              while ! pg_isready -U root -h {{ .Release.Name }}-cockroachdb -p 26257; do sleep 1; done;
              psql --file=/tmp/schema.sql -U root -h {{ .Release.Name }}-cockroachdb -p 26257
        volumeMounts:
          - name: sqlschema
            subPath: schema.sql
            mountPath: /tmp/schema.sql
      volumes:
        - name: sqlschema
          configMap:
            name: {{ include "voltaserve.fullname" . }}-sqlschema
      restartPolicy: OnFailure
  backoffLimit: 30
{{- end }}