apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voltaserve.fullname" . }}-language
  labels:
    {{- include "voltaserve-language.labels" . | nindent 4 }}
spec:
  replicas: {{ default .Values.language.deployment.replicaCount 1}}
  selector:
    matchLabels:
      {{- include "voltaserve-language.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.language.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "voltaserve-language.labels" . | nindent 8 }}
        {{- with .Values.language.deployment.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.imagePullSecrets }}
        {{- with .Values.imagePullSecrets }}
        imagePullSecrets:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if .Values.language.deployment.security }}
      {{- if .Values.language.deployment.security.securityContext }}
      securityContext:
        {{- toYaml .Values.language.deployment.security.securityContext | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ include "voltaserve.fullname" . }}
          {{- if .Values.language.deployment.security }}
          {{- if .Values.language.deployment.security.podSecurityContext }} 
          securityContext:
            {{- toYaml .Values.language.deployment.security.podSecurityContext | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.language.image }}
            image: {{ default .Values.language.image.repository "voltaserve/language" }}:{{ default .Values.language.deployment.tag "latest" }}
          {{- else }}
            image: voltaserve/language: {{ default .Chart.AppVersion "latest" }}
          {{- end }}
          imagePullPolicy: {{ .Values.language.deployment.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.language.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ default .Values.language.deployment.livenessProbePath "/v2/health" }}
              port: {{ .Values.language.service.targetPort }}
            initialDelaySeconds: 300
          readinessProbe:
            httpGet:
              path: {{ default .Values.language.deployment.readinessProbePath "/v2/health" }}
              port: {{ .Values.language.service.targetPort }}
            initialDelaySeconds: 15
          {{- if .Values.language.deployment.resources }}
          resources:
            {{- toYaml .Values.language.deployment.resources | nindent 12 }}
          {{- end }}
          {{- with .Values.language.deployment.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.language.deployment.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.language.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.language.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.language.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}