apiVersion: v1
kind: Service
metadata:
  name: {{ include "voltaserve.fullname" . }}-language
  labels:
    {{- include "voltaserve-language.labels" . | nindent 4 }}
spec:
  ipFamilyPolicy: SingleStack
  type: {{ .Values.language.service.type }}
  clusterIP: "None"
  ports:
    - port: {{ .Values.language.service.port }}
      targetPort: {{ .Values.language.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "voltaserve-language.selectorLabels" . | nindent 6 }}