apiVersion: v1
kind: Service
metadata:
  name: {{ include "voltaserve-language.fullname" . }}
  labels:
    {{- include "voltaserve-language.labels" . | nindent 4 }}
spec:
  ipFamilyPolicy: SingleStack
  type: {{ .Values.language.service.type }}
  clusterIP: "None"
  ports:
    - port: {{ .Values.language.service.port }}
      targetPort: 8084
      protocol: TCP
      name: http
  selector:
    {{- include "voltaserve-language.selectorLabels" . | nindent 6 }}