{{- $fullname :=  include "voltaserve.fullname" . }}
{{- $securityApikeyName := printf "%s-%s" $fullname "security-apikey" }}
{{- $jwtSignKeyName := printf "%s-%s" $fullname "jwt-signkey" }}
{{- $securityApikey := default (randAlphaNum 27) .Values.general.secrets.api.SECURITY_API_KEY | b64enc | quote }}
{{- if not .Values.general.secrets.api.SECURITY_API_KEY }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $securityApikeyName) }}
{{- if $existingSecret }}
{{- $securityApikey = index $existingSecret.data $securityApikeyName}}
{{- end -}}
{{- end -}}
{{- $jwtSignKey := default (randAlphaNum 50) .Values.general.secrets.jwt.SECURITY_JWT_SIGNING_KEY | b64enc | quote }}
{{- if not .Values.general.secrets.jwt.SECURITY_JWT_SIGNING_KEY }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $jwtSignKeyName) }}
{{- if $existingSecret }}
{{- $jwtSignKey = index $existingSecret.data $jwtSignKeyName}}
{{- end -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $securityApikeyName }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  SECURITY_API_KEY: {{ $securityApikey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $jwtSignKeyName }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  SECURITY_JWT_SIGNING_KEY: {{ $jwtSignKey }}
  TOKEN_JWT_SIGNING_KEY: {{ $jwtSignKey }}