{{- if .Values.voltaserve.ingress.enabled }}
{{- if and .Values.voltaserve.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.voltaserve.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.voltaserve.ingress.annotations "kubernetes.io/ingress.class" .Values.voltaserve.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "voltaserve-ui.fullname" . }}
  labels:
    {{- include "voltaserve.commonLabels" . | nindent 4 }}
  {{- with .Values.voltaserve.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.voltaserve.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.voltaserve.ingress.className }}
  {{- end }}
  {{- if.Values.voltaserve.ingress.tls }}
  {{- if .Values.voltaserve.ingress.tls.enabled }}
  tls:
  - hosts:
      - {{ .Values.voltaserve.ingress.host }}
    {{- if .Values.voltaserve.ingress.tls.uiSecretName }}
    secretName: {{ .Values.voltaserve.ingress.tls.uiSecretName }}
    {{- else }}
    secretName: {{ include "voltaserve-ui.fullname" . }}-cert
    {{- end }}
  {{- end }}
  {{- end }}
  rules:
  - host: {{ .Values.voltaserve.ingress.host }}
    http:
      paths:
      - path: /
        {{- if and (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
        pathType: ImplementationSpecific
        {{- end }}
        backend:
          {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          service:
            name: {{ include "voltaserve-ui.fullname" . }}
            port:
              number: {{ .Values.ui.service.port }}
          {{- else }}
          serviceName: {{ include "voltaserve-ui.fullname" . }}
          servicePort: {{ .Values.ui.service.port }}
          {{- end }}
---
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "voltaserve-webdav.fullname" . }}
  labels:
    {{- include "voltaserve.commonLabels" . | nindent 4 }}
  {{- with .Values.voltaserve.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.voltaserve.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.voltaserve.ingress.className }}
  {{- end }}
  {{- if .Values.voltaserve.ingress.tls }}
  {{- if .Values.voltaserve.ingress.tls.enabled }}
  tls:
  - hosts:
      - {{ .Values.voltaserve.ingress.webdavHost }}
    {{- if .Values.voltaserve.ingress.tls.webdavSecretName }}
    secretName: {{ .Values.voltaserve.ingress.tls.webdavSecretName }}
    {{- else }}
    secretName: {{ include "voltaserve-webdav.fullname" . }}-cert
    {{- end }}
  {{- end }}
  {{- end }}
  rules:
  - host: {{ .Values.voltaserve.ingress.webdavHost }}
    http:
      paths:
      - path: /
        {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
        pathType: ImplementationSpecific
        {{- end }}
        backend:
          {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          service:
            name: {{ include "voltaserve-webdav.fullname" . }}
            port:
              number: {{ .Values.webdav.service.port }}
          {{- else }}
          serviceName: {{ include "voltaserve-webdav.fullname" . }}
          servicePort: {{ .Values.webdav.service.port }}
          {{- end }}
{{- end }}