{{- if .Values.ingress.enabled -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "voltaserve.fullname" . }}-ui
  labels:
    {{- include "voltaserve.commonLabels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
      - {{ .Values.ingress.host }} 
    secretName: {{ include "voltaserve.fullname" . }}-ui-cert
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }} 
    http:
      paths:
      - path: /
        {{- if and (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
        pathType: ImplementationSpecific
        {{- end }}
        backend:
          {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          service:
            name: {{ include "voltaserve.fullname" . }}-ui
            port:
              number: {{ .Values.ui.service.port }}
          {{- else }}
          serviceName: {{ include "voltaserve.fullname" . }}-ui
          servicePort: {{ .Values.ui.service.port }}
          {{- end }}
---
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "voltaserve.fullname" . }}-webdav
  labels:
    {{- include "voltaserve.commonLabels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
      - {{ .Values.ingress.webdavHost }} 
    secretName: {{ include "voltaserve.fullname" . }}-webdav-cert
  {{- end }}
  rules:
  - host: {{ .Values.ingress.webdavHost }} 
    http:
      paths:
      - path: /
        {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
        pathType: ImplementationSpecific
        {{- end }}
        backend:
          {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          service:
            name: {{ include "voltaserve.fullname" . }}-webdav
            port:
              number: {{ .Values.webdav.service.port }}
          {{- else }}
          serviceName: {{ include "voltaserve.fullname" . }}-webdav
          servicePort: {{ .Values.webdav.service.port }}
          {{- end }}
{{- end }}