apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "voltaserve-ui.fullname" . }}
data:
  {{- if .Values.ui.envs }}
    {{- range $k,$v := .Values.ui.envs }}
      {{$k }}: {{ default "" $v | quote }}
    {{- end }}
  {{- end }}
  {{- if .Values.general.sharedEnvs }}
    {{- range $k,$v := .Values.general.sharedEnvs }}
      {{$k }}: {{ default "" $v | quote }}
    {{- end }}
  {{- end }}
  API_URL: http://{{ include "voltaserve-api.fullname" . }}.{{.Release.Namespace}}.svc.{{ .Values.clusterDomain | default "cluster.local" }}:{{ .Values.api.service.port }}
  IDP_URL: http://{{ include "voltaserve-idp.fullname" . }}.{{.Release.Namespace}}.svc.{{ .Values.clusterDomain | default "cluster.local" }}:{{ .Values.idp.service.port }}