apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voltaserve-ui.fullname" . }}
  labels:
    {{- include "voltaserve-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ui.deployment.replicaCount | default 1}}
  selector:
    matchLabels:
      {{- include "voltaserve-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/idp/configmap.yaml") . | sha256sum }}
        {{- with .Values.ui.deployment.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "voltaserve-ui.labels" . | nindent 8 }}
        {{- with .Values.ui.deployment.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.imagePullSecrets }}
        {{- with .Values.imagePullSecrets }}
        imagePullSecrets:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if .Values.ui.deployment.security }}
      {{- if .Values.ui.deployment.security.securityContext }}
      securityContext:
        {{- toYaml .Values.ui.deployment.security.securityContext | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
        - name: main
          {{- if .Values.ui.deployment.security }}
          {{- if .Values.ui.deployment.security.podSecurityContext }} 
          securityContext:
            {{- toYaml .Values.ui.deployment.security.podSecurityContext | nindent 12 }}
          {{- end }}
          {{- end }}
          image: {{ .Values.ui.image.repository | default "voltaserve/ui" }}:{{ .Values.ui.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.ui.deployment.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.ui.deployment.livenessProbePath | default "/v2/health" }}
              port: 3000
            initialDelaySeconds: 300
          readinessProbe:
            httpGet:
              path: {{ .Values.ui.deployment.readinessProbePath | default "/v2/health" }}
              port: 3000
            initialDelaySeconds: 15
          {{- if .Values.ui.deployment.resources }}
          resources:
            {{- toYaml .Values.ui.deployment.resources | nindent 12 }}
          {{- end }}
          {{- with .Values.ui.deployment.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
          - configMapRef:
              name: {{ include "voltaserve-ui.fullname" . }}
          {{- if .Values.ui.existingSecret }}
          - secretRef:
              name: {{ .Values.ui.existingSecret }}
          {{- end }}
      {{- with .Values.ui.deployment.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}