apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voltaserve.fullname" . }}-ui
  labels:
    {{- include "voltaserve-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ default .Values.ui.deployment.replicaCount 1}}
  selector:
    matchLabels:
      {{- include "voltaserve-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/idp/configmap.yaml") . | sha256sum }}
        {{- with .Values.ui.deployment.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "voltaserve-ui.labels" . | nindent 8 }}
        {{- with .Values.ui.deployment.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.imagePullSecrets }}
        {{- with .Values.imagePullSecrets }}
        imagePullSecrets:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if .Values.ui.deployment.security }}
      {{- if .Values.ui.deployment.security.securityContext }}
      securityContext:
        {{- toYaml .Values.ui.deployment.security.securityContext | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ include "voltaserve.fullname" . }}
          {{- if .Values.ui.deployment.security }}
          {{- if .Values.ui.deployment.security.podSecurityContext }} 
          securityContext:
            {{- toYaml .Values.ui.deployment.security.podSecurityContext | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.ui.image }}
            image: {{ default .Values.ui.image.repository "voltaserve/ui" }}:{{ default .Values.ui.deployment.tag "latest" }}
          {{- else }}
            image: voltaserve/ui: {{ default .Chart.AppVersion "latest" }}
          {{- end }}
          imagePullPolicy: {{ .Values.ui.deployment.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ui.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ default .Values.ui.deployment.livenessProbePath "/v2/health" }}
              port: {{ .Values.ui.service.targetPort }}
            initialDelaySeconds: 300
          readinessProbe:
            httpGet:
              path: {{ default .Values.ui.deployment.readinessProbePath "/v2/health" }}
              port: {{ .Values.ui.service.targetPort }}
            initialDelaySeconds: 15
          {{- if .Values.ui.deployment.resources }}
          resources:
            {{- toYaml .Values.ui.deployment.resources | nindent 12 }}
          {{- end }}
          {{- with .Values.ui.deployment.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
          - configMapRef:
              name: {{ include "voltaserve.fullname" . }}-ui
      {{- with .Values.ui.deployment.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}