apiVersion: v1
kind: Service
metadata:
  name: {{ include "voltaserve-ui.fullname" . }}
  labels:
    {{- include "voltaserve-ui.labels" . | nindent 4 }}
  {{- with .Values.ui.service.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  ipFamilyPolicy: SingleStack
  type: {{ .Values.ui.service.type }}
  clusterIP: "None"
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "voltaserve-ui.selectorLabels" . | nindent 6 }}