apiVersion: v1
kind: Service
metadata:
  name: {{ include "voltaserve.fullname" . }}-ui
  labels:
    {{- include "voltaserve-ui.labels" . | nindent 4 }}
spec:
  ipFamilyPolicy: SingleStack
  type: {{ .Values.ui.service.type }}
  clusterIP: "None"
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "voltaserve-ui.selectorLabels" . | nindent 6 }}