apiVersion: v1
kind: Secret
metadata:
  name: {{ include "voltaserve-console.fullname" . }}
type: Opaque
data:
  {{- if .Values.general.secrets.sharedSecrets }}
    {{- range $k,$v := .Values.general.sharedEnvs }}
      {{$k }}: {{ default "" $v | b64enc | quote }}
    {{- end }}
  {{- end }}
  SMTP_USERNAME: {{ .Values.general.secrets.smtp.SMTP_USERNAME | b64enc | quote }}
  SMTP_PASSWORD: {{ .Values.general.secrets.smtp.SMTP_PASSWORD | b64enc | quote }}
  S3_ACCESS_KEY: {{ .Values.general.secrets.s3.S3_ACCESS_KEY | default "voltaserve" | b64enc | quote }}
  S3_SECRET_KEY: {{ .Values.general.secrets.s3.S3_SECRET_KEY | default "voltaserve" | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.general.secrets.database.POSTGRES_PASSWORD | default "voltaserve" | b64enc | quote }}