apiVersion: v1
kind: Service
metadata:
  name: {{ include "voltaserve-api.fullname" . }}
  labels:
    {{- include "voltaserve-api.labels" . | nindent 4 }}
spec:
  ipFamilyPolicy: SingleStack
  type: {{ .Values.api.service.type }}
  clusterIP: "None"
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "voltaserve-api.selectorLabels" . | nindent 6 }}