apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "voltaserve-mosaic.fullname" . }}
data:
  {{- if .Values.mosaic.envs }}
    {{- range $k,$v := .Values.mosaic.envs }}
      {{$k }}: {{ default "" $v | quote }}
    {{- end }}
  {{- end }}
  {{- if .Values.minio.enabled }}
  S3_URL: {{ .Release.Name }}-minio.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain | default "cluster.local" }}:9000
  {{- else }}
  S3_URL: {{ .Values.general.envs.S3_URL }}
  {{- end  }}
  S3_SECURE: {{ .Values.general.envs.S3_SECURE | quote }}
