apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "voltaserve-mosaic.fullname" . }}
data:
  {{- if .Values.mosaic.envs }}
    {{- range $k,$v := .Values.mosaic.envs }}
      {{$k }}: {{ default "" $v | quote }}
    {{- end }}
  {{- end }}
  {{- if .Values.general.sharedEnvs }}
    {{- range $k,$v := .Values.general.sharedEnvs }}
      {{$k }}: {{ default "" $v | quote }}
    {{- end }}
  {{- end }}
  {{- if .Values.minio.enabled }}
  S3_URL: {{ .Release.Name }}-minio.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain | default "cluster.local" }}:9000
  S3_SECURE: "false"
  S3_REGION: "us-east-1"
  {{- else }}
  S3_URL: {{ .Values.general.s3.S3_URL }}
  S3_SECURE: {{ .Values.general.s3.S3_SECURE | default false | quote }}
  S3_REGION: {{ .Values.general.s3.S3_REGION | default "us-east-1" | quote }}
  {{- end  }}
  LIMITS_MULTIPART_BODY_LENGTH_LIMIT_MB: {{ .Values.general.limits.LIMITS_MULTIPART_BODY_LENGTH_LIMIT_MB | default 5000 | quote }}
