apiVersion: v1
kind: Service
metadata:
  name: {{ include "voltaserve.fullname" . }}-mosaic
  labels:
    {{- include "voltaserve-mosaic.labels" . | nindent 4 }}
spec:
  ipFamilyPolicy: SingleStack
  type: {{ .Values.mosaic.service.type }}
  clusterIP: "None"
  ports:
    - port: {{ .Values.mosaic.service.port }}
      targetPort: 8085
      protocol: TCP
      name: http
  selector:
    {{- include "voltaserve-mosaic.selectorLabels" . | nindent 6 }}