apiVersion: v1
kind: Service
metadata:
  name: {{ include "voltaserve-mosaic.fullname" . }}
  labels:
    {{- include "voltaserve-mosaic.labels" . | nindent 4 }}
  {{- if or .Values.mosaic.service.annotations (.Values.global).serviceAnnotations }}
  annotations:
  {{- with .Values.mosaic.service.annotations }}
    {{ toYaml . | indent 4 }}
  {{- end }}
  {{- with (.Values.globals).serviceAnnotations }}
    {{ toYaml . | indent 4 }}
  {{- end }}
  {{- end }}
spec:
  ipFamilyPolicy: SingleStack
  type: {{ .Values.mosaic.service.type }}
  clusterIP: "None"
  ports:
    - port: {{ .Values.mosaic.service.port }}
      targetPort: 8085
      protocol: TCP
      name: http
  selector:
    {{- include "voltaserve-mosaic.selectorLabels" . | nindent 6 }}