# Copyright 2024 Piotr Łoboda.
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the GNU Affero General Public License v3.0 only, included in the file
# licenses/AGPL.txt.

name: Lint Voltaserve official Helm Chart!

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - 'main'
    paths:
      - 'templates/**'
      - 'files/**'
      - '.helmignore'
      - 'Chart.yaml'
      - 'values.yaml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Checkout Repository
        uses: Azure/setup-helm@v4.2.0
        
      - name: Build dependencies
        run: helm dependency build .
        
      - name: Lint helm chart
        run: helm lint voltaserve . -f values.yaml
